-- ---------------------------------------------------------------------------
-- DATACONTROL - esquema inicial
--
-- Planta de fritura de papa de Productos Alimenticios Fritomix SAS.
-- Este archivo es la linea base del esquema: crea todas las tablas del
-- sistema. Flyway lo aplica una sola vez y deja registro en la tabla
-- "flyway_schema_history". Nunca se edita un archivo ya aplicado: los
-- cambios posteriores van en un V2__, V3__, etc.
--
-- Convenciones:
--   * Nombres de tablas y columnas en espanol (es el idioma del negocio).
--   * Los ids son IDENTITY (los genera PostgreSQL).
--   * Las fechas/horas con zona se guardan en UTC (timestamptz); la
--     conversion a hora de Colombia se hace en la aplicacion.
--   * "eliminado" = borrado suave: la fila deja de verse en pantallas,
--     analisis y exportaciones, pero se conserva para auditoria.
-- ---------------------------------------------------------------------------

-- === Identidad =============================================================

CREATE TABLE roles (
    id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(30)  NOT NULL UNIQUE,
    nombre VARCHAR(100) NOT NULL
);

COMMENT ON TABLE roles IS 'Roles del sistema: admin, supervisor, operario_horno, operario_saborizado.';
COMMENT ON COLUMN roles.codigo IS 'Identificador interno usado por el codigo para los permisos; no cambia nunca.';

CREATE TABLE usuarios (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_completo   VARCHAR(150) NOT NULL,
    nombre_usuario    VARCHAR(50)  NOT NULL UNIQUE,
    password_hash     VARCHAR(255) NOT NULL,
    rol_id            INTEGER      NOT NULL REFERENCES roles (id),
    activo            BOOLEAN      NOT NULL DEFAULT TRUE,
    fecha_creacion    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    eliminado         BOOLEAN      NOT NULL DEFAULT FALSE,
    eliminado_por_id  INTEGER      NULL REFERENCES usuarios (id),
    fecha_eliminacion TIMESTAMPTZ  NULL
);

COMMENT ON COLUMN usuarios.password_hash IS 'Hash bcrypt. La contrasena en texto plano nunca se guarda.';

CREATE INDEX ix_usuarios_rol ON usuarios (rol_id);

-- === Catalogos =============================================================

CREATE TABLE categorias_producto (
    id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    activo BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE turnos (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre           VARCHAR(50) NOT NULL UNIQUE,
    hora_inicio      TIME        NOT NULL,
    hora_fin         TIME        NOT NULL,
    cruza_medianoche BOOLEAN     NOT NULL DEFAULT FALSE,
    activo           BOOLEAN     NOT NULL DEFAULT TRUE
);

COMMENT ON COLUMN turnos.cruza_medianoche IS 'TRUE para el turno nocturno (ej. 10:00 PM a 6:00 AM).';

CREATE TABLE hornos (
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre               VARCHAR(50)   NOT NULL UNIQUE,
    activo               BOOLEAN       NOT NULL DEFAULT TRUE,
    tipo_aceite          VARCHAR(50)   NULL,
    apto_exportacion     BOOLEAN       NOT NULL DEFAULT FALSE,
    tanque_diametro_cm   NUMERIC(6, 2) NULL,
    litros_por_cm_manual NUMERIC(8, 4) NULL
);

COMMENT ON COLUMN hornos.tanque_diametro_cm IS 'Calibracion estimada: con el diametro la app calcula litros por cm asumiendo un cilindro.';
COMMENT ON COLUMN hornos.litros_por_cm_manual IS 'Calibracion real medida a mano. Si esta presente, tiene prioridad sobre el diametro.';

CREATE TABLE horno_categoria (
    horno_id     INTEGER NOT NULL REFERENCES hornos (id) ON DELETE CASCADE,
    categoria_id INTEGER NOT NULL REFERENCES categorias_producto (id) ON DELETE CASCADE,
    PRIMARY KEY (horno_id, categoria_id)
);

COMMENT ON TABLE horno_categoria IS 'Que categorias puede producir cada horno. Lo configura el administrador.';

CREATE TABLE sabores (
    id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    activo BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE productos (
    id                          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_comercial            VARCHAR(150)  NOT NULL UNIQUE,
    categoria_id                INTEGER       NOT NULL REFERENCES categorias_producto (id),
    activo                      BOOLEAN       NOT NULL DEFAULT TRUE,
    peso_estandar_canastilla_kg NUMERIC(6, 2) NULL
);

COMMENT ON COLUMN productos.peso_estandar_canastilla_kg IS
    'Peso ESTIMADO por canastilla de esta referencia, solo para programar ordenes pedidas en canastillas. El peso real se pesa en saborizado.';

CREATE INDEX ix_productos_categoria ON productos (categoria_id);

CREATE TABLE tipos_desperdicio (
    id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    activo BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE configuracion_planta (
    id                          INTEGER       NOT NULL PRIMARY KEY,
    peso_estandar_bulto_kg      NUMERIC(6, 2) NULL,
    peso_estandar_canastilla_kg NUMERIC(6, 2) NULL,
    CONSTRAINT ck_configuracion_fila_unica CHECK (id = 1)
);

COMMENT ON TABLE configuracion_planta IS 'Tabla de una sola fila (id = 1) con los valores generales de la planta.';

CREATE TABLE muestras_densidad_aceite (
    id                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    horno_id              INTEGER       NOT NULL REFERENCES hornos (id),
    fecha                 DATE          NOT NULL,
    densidad_kg_por_litro NUMERIC(6, 4) NOT NULL,
    usuario_id            INTEGER       NOT NULL REFERENCES usuarios (id),
    fecha_creacion        TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE muestras_densidad_aceite IS
    'La densidad del aceite se obtiene por muestreos y cambia por horno y por fecha; cada registro de horno usa la muestra vigente mas reciente.';

CREATE INDEX ix_muestras_densidad_horno_fecha ON muestras_densidad_aceite (horno_id, fecha DESC);

-- === Produccion ============================================================

CREATE TABLE secuencia_ordenes (
    fecha         DATE    NOT NULL PRIMARY KEY,
    ultimo_numero INTEGER NOT NULL DEFAULT 0
);

COMMENT ON TABLE secuencia_ordenes IS 'Ultimo consecutivo usado por fecha, para numerar ordenes como OP-20260826-0001.';

CREATE TABLE ordenes_produccion (
    id                               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_orden                     VARCHAR(20)    NOT NULL UNIQUE,
    fecha                            DATE           NOT NULL,
    supervisor_id                    INTEGER        NOT NULL REFERENCES usuarios (id),
    turno_id                         INTEGER        NOT NULL REFERENCES turnos (id),
    horno_id                         INTEGER        NOT NULL REFERENCES hornos (id),
    producto_id                      INTEGER        NOT NULL REFERENCES productos (id),
    categoria_id                     INTEGER        NOT NULL REFERENCES categorias_producto (id),
    cantidad_programada              NUMERIC(10, 2) NOT NULL,
    unidad_solicitada                VARCHAR(20)    NOT NULL DEFAULT 'kg',
    cantidad_canastillas_solicitadas NUMERIC(10, 2) NULL,
    destino                          VARCHAR(20)    NOT NULL DEFAULT 'nacional',
    estado                           VARCHAR(20)    NOT NULL DEFAULT 'pendiente',
    hora_inicio                      TIMESTAMPTZ    NULL,
    hora_fin                         TIMESTAMPTZ    NULL,
    fecha_creacion                   TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    eliminado                        BOOLEAN        NOT NULL DEFAULT FALSE,
    eliminado_por_id                 INTEGER        NULL REFERENCES usuarios (id),
    fecha_eliminacion                TIMESTAMPTZ    NULL,
    CONSTRAINT ck_orden_estado_valido
        CHECK (estado IN ('pendiente', 'en_produccion', 'finalizada', 'cancelada')),
    CONSTRAINT ck_orden_destino_valido
        CHECK (destino IN ('nacional', 'exportacion')),
    CONSTRAINT ck_orden_unidad_solicitada_valida
        CHECK (unidad_solicitada IN ('kg', 'canastillas'))
);

-- Regla de negocio critica: un horno NUNCA puede tener dos ordenes en
-- produccion al mismo tiempo. Este indice unico parcial lo garantiza en la
-- base de datos, incluso si el codigo de la aplicacion tuviera un error.
CREATE UNIQUE INDEX ux_un_horno_en_produccion
    ON ordenes_produccion (horno_id)
    WHERE estado = 'en_produccion';

CREATE INDEX ix_ordenes_fecha      ON ordenes_produccion (fecha DESC);
CREATE INDEX ix_ordenes_estado     ON ordenes_produccion (estado);
CREATE INDEX ix_ordenes_supervisor ON ordenes_produccion (supervisor_id);
CREATE INDEX ix_ordenes_horno      ON ordenes_produccion (horno_id);
CREATE INDEX ix_ordenes_producto   ON ordenes_produccion (producto_id);
CREATE INDEX ix_ordenes_categoria  ON ordenes_produccion (categoria_id);

CREATE TABLE registro_horno (
    id                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orden_id                INTEGER        NOT NULL REFERENCES ordenes_produccion (id),
    usuario_id              INTEGER        NOT NULL REFERENCES usuarios (id),
    hora_inicio             TIMESTAMPTZ    NOT NULL,
    hora_fin                TIMESTAMPTZ    NOT NULL,
    cantidad_bultos         NUMERIC(6, 2)  NOT NULL,
    peso_estandar_bulto_kg  NUMERIC(6, 2)  NOT NULL,
    kg_crudos_calculados    NUMERIC(10, 2) NOT NULL,
    operarios_seleccion     SMALLINT       NOT NULL,
    operarios_horno         SMALLINT       NOT NULL,
    nivel_aceite_inicial_cm NUMERIC(6, 2)  NOT NULL,
    nivel_aceite_final_cm   NUMERIC(6, 2)  NOT NULL,
    diferencia_aceite_cm    NUMERIC(6, 2)  NOT NULL,
    temperatura_aceite_c    NUMERIC(5, 2)  NULL,
    litros_por_cm_usado     NUMERIC(8, 4)  NULL,
    volumen_aceite_litros   NUMERIC(10, 2) NULL,
    densidad_aceite_usada   NUMERIC(6, 4)  NULL,
    kg_aceite_consumido     NUMERIC(10, 2) NULL,
    observaciones           TEXT           NULL,
    fecha_creacion          TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    eliminado               BOOLEAN        NOT NULL DEFAULT FALSE,
    eliminado_por_id        INTEGER        NULL REFERENCES usuarios (id),
    fecha_eliminacion       TIMESTAMPTZ    NULL
);

COMMENT ON COLUMN registro_horno.peso_estandar_bulto_kg IS
    'Copia del valor vigente al crear el registro: si la configuracion cambia despues, el historico no se altera.';
COMMENT ON COLUMN registro_horno.kg_aceite_consumido IS
    'Queda NULL si el horno todavia no tiene calibracion de tanque o densidad: no se inventa un valor.';

CREATE INDEX ix_registro_horno_orden ON registro_horno (orden_id);

CREATE TABLE desperdicios (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registro_horno_id   INTEGER       NOT NULL REFERENCES registro_horno (id) ON DELETE CASCADE,
    tipo_desperdicio_id INTEGER       NOT NULL REFERENCES tipos_desperdicio (id),
    cantidad_kg         NUMERIC(8, 2) NOT NULL,
    observacion         TEXT          NULL
);

CREATE INDEX ix_desperdicios_registro ON desperdicios (registro_horno_id);

CREATE TABLE registro_saborizado (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orden_id          INTEGER        NOT NULL REFERENCES ordenes_produccion (id),
    usuario_id        INTEGER        NOT NULL REFERENCES usuarios (id),
    turno_id          INTEGER        NOT NULL REFERENCES turnos (id),
    hora_inicio       TIMESTAMPTZ    NOT NULL,
    hora_fin          TIMESTAMPTZ    NOT NULL,
    sabor_id          INTEGER        NOT NULL REFERENCES sabores (id),
    cantidad_sabor_kg NUMERIC(8, 2)  NOT NULL,
    kg_recibidos      NUMERIC(10, 2) NOT NULL,
    fecha_creacion    TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    eliminado         BOOLEAN        NOT NULL DEFAULT FALSE,
    eliminado_por_id  INTEGER        NULL REFERENCES usuarios (id),
    fecha_eliminacion TIMESTAMPTZ    NULL
);

COMMENT ON TABLE registro_saborizado IS 'Una orden puede tener varias recepciones, cada una con su sabor y su grupo de canastillas.';
COMMENT ON COLUMN registro_saborizado.kg_recibidos IS 'Suma automatica de los pesos reales de las canastillas de esta recepcion.';

CREATE INDEX ix_registro_saborizado_orden ON registro_saborizado (orden_id);
CREATE INDEX ix_registro_saborizado_sabor ON registro_saborizado (sabor_id);

CREATE TABLE canastillas (
    id                     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registro_saborizado_id INTEGER       NOT NULL REFERENCES registro_saborizado (id) ON DELETE CASCADE,
    numero                 SMALLINT      NOT NULL,
    peso_kg                NUMERIC(6, 2) NOT NULL
);

COMMENT ON TABLE canastillas IS 'Peso REAL de cada canastilla pesada por el operario. Nunca un valor asumido.';

CREATE INDEX ix_canastillas_recepcion ON canastillas (registro_saborizado_id);
