-- ---------------------------------------------------------------------------
-- Avisos para el personal de planta.
--
-- Dos momentos disparan un aviso:
--   1) Se crea una orden  -> se avisa a los operarios de horno y saborizado.
--   2) Faltan 15 minutos para que termine el tiempo de produccion programado.
--
-- El aviso del punto 2 NO necesita un proceso en segundo plano: cuando la
-- orden entra en produccion se guarda la fila con "fecha_programada" en el
-- futuro (hora de inicio + horas programadas - 15 min), y la API solo
-- entrega las notificaciones cuya fecha_programada ya llego. Asi no hay
-- ningun demonio que se pueda caer y dejar a la planta sin avisos.
-- ---------------------------------------------------------------------------

CREATE TABLE notificaciones (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- A quien va dirigido el aviso.
    usuario_id       INTEGER      NOT NULL REFERENCES usuarios (id),

    tipo             VARCHAR(40)  NOT NULL,
    titulo           VARCHAR(150) NOT NULL,
    mensaje          TEXT         NOT NULL,

    -- Orden relacionada, para poder abrirla desde el aviso.
    orden_id         INTEGER      NULL REFERENCES ordenes_produccion (id),

    -- Desde cuando debe verse. Igual a la fecha de creacion en los avisos
    -- inmediatos; en el futuro para los programados (15 min antes del fin).
    fecha_programada TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    -- Se marca cuando la persona ya la vio (y ya sono la alarma).
    leida            BOOLEAN      NOT NULL DEFAULT FALSE,
    fecha_creacion   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT ck_notificacion_tipo_valido
        CHECK (tipo IN ('orden_creada', 'produccion_por_terminar'))
);

COMMENT ON TABLE notificaciones IS
    'Avisos por usuario. Las programadas aparecen cuando fecha_programada <= ahora.';
COMMENT ON COLUMN notificaciones.fecha_programada IS
    'Momento desde el cual el aviso debe entregarse. Permite programar el aviso de "faltan 15 minutos" sin procesos en segundo plano.';

-- Consulta caliente: "dame lo pendiente de este usuario que ya toca mostrar".
CREATE INDEX ix_notificaciones_pendientes
    ON notificaciones (usuario_id, leida, fecha_programada DESC);

-- Evita duplicar el mismo aviso para la misma orden y persona (por ejemplo,
-- si se reinicia una orden o si dos peticiones corren a la vez).
CREATE UNIQUE INDEX ux_notificacion_unica_por_orden
    ON notificaciones (usuario_id, orden_id, tipo)
    WHERE orden_id IS NOT NULL;
